apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 80Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain 
  csi:  # aws 
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-0827a006ab9fc4b08
  nodeAffinity: # aws
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values: 
              - ap-northeast-2a