apiVersion: v1
kind: Pod
metadata:
  name: apache-pod
  namespace: my-ns
  labels:
    name: apache
    tier: frontend
    app: apache
spec:
  containers:
  - name: apache-container
    image: bitnami/apache
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
