apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-dp
spec:
  selector:
    matchLabels:
      app: httpd-pod
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2 
      maxUnavailable: 3 
  template:
    metadata:
      labels:
        app: httpd-pod
    spec:
      containers:
      - name: httpd-container
        image: httpd:2-alpine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
