apiVersion: v1
kind: Pod
metadata:
  name: nginx # pod 
  labels:
    name: nginx
spec:
  containers:
  - name: nginx # container 
    image: nginx:1.9.1
    resources: 
      limits: # 스케쥴링 효율에 중요. 
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8081 
